### ISSUE TITLE
Alfresco container start error - AlfatecSignUtils ?

### ISSUE THREAD

**Issue by lonestaritaly** [Alfresco/alfresco-docker-installer#175]
Hello,

any idea what this error could be?
the installation is an upgrade from working alfresco 7.3.1, done by copying the /data folder from the previous stack, reusing previous docker-compose.yml and new 7.4 env file.

```
alfresco_1            | 2023-08-15T13:05:07,338 [] INFO  [management.subsystems.ChildApplicationContextFactory] [main] Stopping 'Authentication' subsystem, ID: [Authentication, managed, alfinst]
alfresco_1            | 2023-08-15T13:05:07,339 [] INFO  [management.subsystems.ChildApplicationContextFactory] [main] Stopped 'Authentication' subsystem, ID: [Authentication, managed, alfinst]
alfresco_1            | 2023-08-15T13:05:07,340 [] INFO  [management.subsystems.ChildApplicationContextFactory] [main] Stopping 'Authentication' subsystem, ID: [Authentication, managed, external1]
alfresco_1            | 2023-08-15T13:05:07,340 [] INFO  [management.subsystems.ChildApplicationContextFactory] [main] Stopped 'Authentication' subsystem, ID: [Authentication, managed, external1]
alfresco_1            | 2023-08-15T13:05:07,348 [] ERROR [web.context.ContextLoader] [main] Context initialization failed
alfresco_1            | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'AlfatecSignUtils' defined in class path resource [alfresco/module/esign-cert-repo/context/service-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [es.alfatec.alfresco.AlfatecSignUtils]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Logger
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:920) ~[spring-context-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:399) ~[spring-web-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:278) ~[spring-web-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web-5.3.27.jar:5.3.27]
alfresco_1            |         at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70) ~[classes/:21.14]
alfresco_1            |         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4493) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4939) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:683) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:124) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:142) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:132) ~[catalina.jar:9.0.73]
alfresco_1            |         at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:656) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:662) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1184) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1932) ~[catalina.jar:9.0.73]
alfresco_1            |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
alfresco_1            |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
alfresco_1            |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.73]
alfresco_1            |         at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123) ~[?:?]
alfresco_1            |         at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1094) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:476) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1617) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:318) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:898) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[catalina.jar:9.0.73]
alfresco_1            |         at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
alfresco_1            |         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.73]
alfresco_1            |         at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[?:?]
alfresco_1            |         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:871) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardService.startInternal(StandardService.java:428) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:917) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.Catalina.start(Catalina.java:772) ~[catalina.jar:9.0.73]
alfresco_1            |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
alfresco_1            |         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
alfresco_1            |         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347) ~[bootstrap.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) ~[bootstrap.jar:9.0.73]
alfresco_1            | Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [es.alfatec.alfresco.AlfatecSignUtils]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/log4j/Logger
alfresco_1            |         at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$instantiateBean$3(AbstractAutowireCapableBeanFactory.java:1322) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         ... 59 more
alfresco_1            | Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
alfresco_1            |         at es.alfatec.alfresco.AlfatecSignUtils.<init>(AlfatecSignUtils.java:42) ~[esign-cert-repo-1.8.2.jar:?]
alfresco_1            |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
alfresco_1            |         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
alfresco_1            |         at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
alfresco_1            |         at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$instantiateBean$3(AbstractAutowireCapableBeanFactory.java:1322) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         ... 59 more
alfresco_1            | Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
alfresco_1            |         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1412) ~[catalina.jar:9.0.73]
alfresco_1            |         at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1220) ~[catalina.jar:9.0.73]
alfresco_1            |         at es.alfatec.alfresco.AlfatecSignUtils.<init>(AlfatecSignUtils.java:42) ~[esign-cert-repo-1.8.2.jar:?]
alfresco_1            |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
alfresco_1            |         at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
alfresco_1            |         at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
alfresco_1            |         at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
alfresco_1            |         at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$instantiateBean$3(AbstractAutowireCapableBeanFactory.java:1322) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.3.27.jar:5.3.27]
alfresco_1            |         ... 59 more
alfresco_1            | 15-Aug-2023 13:05:07.360 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
alfresco_1            | 15-Aug-2023 13:05:07.364 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/alfresco] startup failed due to previous errors

```

**Comment by kusannaghi** [comment]
I have the same problem, but i don't understand what i need to do to solve the problem, sorry. I run yo alfresco-docker-installer and when it has finish i run docker compose up. And not work. What have i do it?
