### ISSUE TITLE
project creation error

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#184]
I am facing below error during project creation.

× An error occured while running alfresco-docker-installer:app#writing
Error alfresco-docker-installer

error:0308010C:digital envelope routines::unsupported
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_OSSL_EVP_UNSUPPORTED')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:188:24)
    at onError (C:\Users\Sanjay\AppData\Roaming\npm\node_modules\yo\lib\cli.js:117:11)
    at C:\Users\Sanjay\AppData\Roaming\npm\node_modules\yo\lib\cli.js:168:54
    at async init (C:\Users\Sanjay\AppData\Roaming\npm\node_modules\yo\lib\cli.js:168:5)
    at async pre (C:\Users\Sanjay\AppData\Roaming\npm\node_modules\yo\lib\cli.js:83:3)
    at async C:\Users\Sanjay\AppData\Roaming\npm\node_modules\yo\lib\cli.js:193:3

**Comment by aborroy** [comment]
Please, apply https://github.com/Alfresco/alfresco-docker-installer/issues/164
