### ISSUE TITLE
Module is-ci not found

### ISSUE THREAD

**Issue by sHHHk** [Alfresco/alfresco-docker-installer#195]
Hi everyone,

I've downloaded the alfresco-docker-installer module, however it always throws an error saying that the is-ci module is not being found :(. I don't know what to do

The alfresco-6.2 folder (where the docker-compose.yml file is being produced) is empty as mentioned in the README.md 

`root@srv:~/alfresco-6.2# export NODE_OPTIONS=--openssl-legacy-provider
root@srv:~/alfresco-6.2# export PATH=$PATH:/root/node-v21.7.1-linux-x64/bin
root@srv:~/alfresco-6.2# yo alfresco-docker-installer
node:internal/modules/cjs/loader:1145
  throw err;
  ^

Error: Cannot find module 'is-ci'
Require stack:
- /root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/update-notifier/index.js
- /root/node-v21.7.1-linux-x64/lib/node_modules/yo/lib/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1142:15)
    at Module._load (node:internal/modules/cjs/loader:983:27)
    at Module.require (node:internal/modules/cjs/loader:1230:19)
    at require (node:internal/modules/helpers:179:18)
    at lazy (/root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/import-lazy/index.js:2:51)
    at /root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/import-lazy/index.js:10:11
    at new UpdateNotifier (/root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/update-notifier/index.js:46:4)
    at module.exports (/root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/update-notifier/index.js:183:25)
    at updateCheck (/root/node-v21.7.1-linux-x64/lib/node_modules/yo/lib/cli.js:54:20)
    at Object.<anonymous> (/root/node-v21.7.1-linux-x64/lib/node_modules/yo/lib/cli.js:190:1) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/node-v21.7.1-linux-x64/lib/node_modules/yo/node_modules/update-notifier/index.js',
    '/root/node-v21.7.1-linux-x64/lib/node_modules/yo/lib/cli.js'
  ]
}

Node.js v21.7.1
`

**Comment by aborroy** [comment]
Use Node 14

**Comment by martinpetermichael** [comment]
Hi,

I've the same Problem. Used Node 14 and Node 16. but same Problem. I also tryed to install is ci - but didn't help.

**Comment by aborroy** [comment]
Try re-installing yo:

```
npm uninstall -g yo
npm install -g yo
```

**Comment by martinpetermichael** [comment]
Hi,

thank you. That did the trick. My mistake was - i used the Install instructions from the node Website. Now I did:
sudo apt install nodejs -y
sudo apt install npm -y
sudo npm install -g yo
