### ISSUE TITLE
Exception after last step of the generator: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by eleaese** [Alfresco/alfresco-docker-installer#199]
Using the last version that includes Alfresco 23.2 fails after entering all options:
```
? Which ACS version do you want to use? 23.2
? How may GB RAM are available for Alfresco (16 is minimum required)? 16
? Do you want to use HTTPs for Web Proxy? No
? What is the name of your server? localhost
? Choose the password for your admin user admin
? What HTTP port do you want to use (all the services are using the same port)? 8080
? Do you want to use FTP (port 2121)? No
? Do you want to use MariaDB instead of PostgreSQL? No
? Are you using different languages (this is the most common scenario)? Yes
? Do you want to search in the content of the documents? Yes
? Would you like to use Shared Secret or HTTPs for Alfresco-SOLR communication? secret
? Do you want to use the Events service (ActiveMQ)? No
? Do you want to create an internal SMTP server? No
? Do you want to create an internal LDAP server? No
? Select the addons to be installed: JavaScript Console 0.7, Order of the Bee Support Tools 1.2.2.0
? Do you want Docker to manage volume storage (recommended when dealing with permission issues)? No
? Do you want to use a start script? Yes
? Do you want to get the script to create host volumes? Yes
✖ An error occured while running alfresco-docker-installer:app#writing
Error alfresco-docker-installer 

error:0308010C:digital envelope routines::unsupported
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('ERR_OSSL_EVP_UNSUPPORTED')
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at process.exit (node:internal/process/per_thread:182:24)
    at onError (/usr/local/lib/node_modules/yo/lib/cli.js:117:11)
    at /usr/local/lib/node_modules/yo/lib/cli.js:168:54
    at async init (/usr/local/lib/node_modules/yo/lib/cli.js:168:5)
    at async pre (/usr/local/lib/node_modules/yo/lib/cli.js:83:3)
    at async /usr/local/lib/node_modules/yo/lib/cli.js:193:3
```

Tested with node versions v18.19.0, v20.11.1 and v22.2.0. On each node version run:
```
npm install -g yo generator-alfresco-docker-installer
yo alfresco-docker-installer

```

**Comment by eleaese** [comment]
My fault, I didn't set NODE_OPTIONS

**Comment by eleaese** [comment]
My fault, I didn't set NODE_OPTIONS=--openssl-legacy-provider.
