### ISSUE TITLE
start script error

### ISSUE THREAD

**Issue by strarsis** [Alfresco/alfresco-docker-installer#49]
When using the `start.sh` script:
````
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at Object.resolve (path.js:978:47)
    at patchProcessObject (internal/bootstrap/pre_execution.js:92:28)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:16:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
Waiting failed -> exit 1
````

**Comment by aborroy** [comment]
Probably @mmuller88 can help with that.

**Comment by strarsis** [comment]
@aborroy: Has this been fixed now (recent releases)?

**Comment by aborroy** [comment]
I re-tested this with latest version and it seems to be working. Do you have additional feedback on it?

**Comment by strarsis** [comment]
@aborroy: Awesome! I will try this out soon.
